/* Generated By:JJTree: Do not edit this line. ASTArrayElement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayElement extends SimpleNode {
  private String name;
  private Token t;

  public ASTArrayElement(int id) {
    super(id);
  }

  public ASTArrayElement(YAL2JVM p, int id) {
    super(p, id);
  }
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public void setToken(Token t) {
    this.t = t;
  }

  public String toString() {
    String test = super.toString();
    return test + " " + name;
  }

  @Override
  public boolean analyse(Table currentTable) {
    if(currentTable.lookup(name) == null) {
      System.out.println("ArrayElement Save! " +name);
      currentTable.save(new Symbol(name, 1, "Variable"));
      return true;
    }
    return true;
  }

  public int checkScalarOrArray(Table currentTable) {
    return 1;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YAL2JVMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=84907a8537e7b97a089d8ff63829828b (do not edit this line) */
