/* Generated By:JJTree: Do not edit this line. ASTArrayElement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayElement extends SimpleNode {
  public ASTArrayElement(int id) {
    super(id);
  }

  public ASTArrayElement(YAL2JVM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=05ca1048a68500ba0c366ef749681324 (do not edit this line) */
