/* Generated By:JJTree: Do not edit this line. ASTArgument.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgument extends SimpleNode {
  private String number;
  private String name;
  private String string;
  private Token t;

  public ASTArgument(int id) {
    super(id);
  }

  public ASTArgument(YAL2JVM p, int id) {
    super(p, id);
  }

  public String getString() {
    return string;
  }


  public void setString(String string) {
    this.string = string;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public void setToken(Token t) {
    this.t = t;
  }

  public String toString() {
    String test = super.toString();
    if(this.name != null)
      test += " " + name;
    if(this.number != null)
      test += " " + number;
    return test;
  }

  @Override
 public boolean analyse(Table currentTable) {

    if(this.name != null)
    {
      if(currentTable.lookup(name) == null) {
        System.out.println("Variable Doesn't exist! " +name + " at line: " + t.beginLine);
        return false;
      }

      return true;
    }
    else if (this.number != null || this.string != null){
      return true;
      //caso de ser constante
      //necessário guardar para tamanhos de array
    }


    return true;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(YAL2JVMVisitor visitor, Object data) {

    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5a41fd65cc3c3797a095c5e758e4aac8 (do not edit this line) */
