/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgumentList extends SimpleNode {
  public ASTArgumentList(int id) {
    super(id);
  }

  public ASTArgumentList(YAL2JVM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=057d334dc5ec375f82dd0cf6863ba256 (do not edit this line) */
