/* Generated By:JJTree: Do not edit this line. ASTArraySize.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArraySize extends SimpleNode {
  private String name;

  public ASTArraySize(int id) {
    super(id);
  }

  public ASTArraySize(YAL2JVM p, int id) {
    super(p, id);
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String toString() {
    String test = super.toString();
    if(name != null)
      return test + " " + name;
    return test;
  }

  public int checkScalarOrArray(Table currentTable) {
    return 1;
  }
  /** Accept the visitor. **/
  public Object jjtAccept(YAL2JVMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ebc7d9babd27da05f08a6428c80349c6 (do not edit this line) */
