/* Generated By:JJTree: Do not edit this line. ASTerror_control.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTerror_control extends SimpleNode {
  public ASTerror_control(int id) {
    super(id);
  }

  public ASTerror_control(YAL2JVM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8e185536e73f7c9ccfbdd8345738ebe3 (do not edit this line) */
