/* Generated By:JJTree: Do not edit this line. ASTLhs.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLhs extends SimpleNode {
  public ASTLhs(int id) {
    super(id);
  }

  public ASTLhs(YAL2JVM p, int id) {
    super(p, id);
  }

  public boolean analyse(Table currentTable) {
    boolean x = true;
    for(int i = 0; i < this.jjtGetNumChildren(); i++) {
      boolean b = this.jjtGetChild(i).analyseLeft(currentTable);
      if(!b)
        x = false;
    }
    return x;
  }

  public boolean analyse(Table currentTable, int j) {
    boolean x = true;
    for(int i = 0; i < this.jjtGetNumChildren(); i++) {
      boolean b = this.jjtGetChild(i).analyseLeft(currentTable, j);
      if(!b)
        x = false;
    }
    return x;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YAL2JVMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=745778a121298708cddba7a03d06e88a (do not edit this line) */
