/* Generated By:JJTree: Do not edit this line. ASTModule.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTModule extends SimpleNode {
  private String name;

  public ASTModule(int id) {
    super(id);
  }

  public ASTModule(YAL2JVM p, int id) {
    super(p, id);
  }
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  public String toString() {
    String test = super.toString();
    return test + " " + name;
  }

  @Override
  public boolean analyse(Table currentTable) {
    Table table = new Table(currentTable);

    boolean x = true;
    for(int i = 0; i < this.jjtGetNumChildren(); i++) {
      boolean b = this.jjtGetChild(i).prepareModule(table);
      if(!b)
        x = false;
    }

    for(int i = 0; i < this.jjtGetNumChildren(); i++) {
      boolean b = this.jjtGetChild(i).analyse(table);
      if(!b)
        x = false;
    }
    return x;

  }


  /** Accept the visitor. **/
  public Object jjtAccept(YAL2JVMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=420c897347ceedc538334245df9e64ce (do not edit this line) */
