/* Generated By:JJTree: Do not edit this line. ASTRhs.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRhs extends SimpleNode {
  private String op;
  private String scalarOrArray;
  public ASTRhs(int id) {
    super(id);
  }

  public ASTRhs(YAL2JVM p, int id) {
    super(p, id);
  }
  public String getOp() {
    return op;
  }
  public void setOp(String op) {
    this.op = op;
  }

  public String toString() {
    String test = super.toString();
    if(op != null)
      return test + " " + op;
    return test;
  }

  public int checkScalarOrArray(Table currentTable) {
    return this.jjtGetChild(0).checkScalarOrArray(currentTable);
  }
  /** Accept the visitor. **/
  public Object jjtAccept(YAL2JVMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=52ed9e06f3d670103e31df92fa26de22 (do not edit this line) */
