/* Generated By:JJTree: Do not edit this line. ASTStmt.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStmt extends SimpleNode {
  public ASTStmt(int id) {
    super(id);
  }

  public ASTStmt(YAL2JVM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=452557bbcde865e818e91a27824c7b50 (do not edit this line) */
