/* Generated By:JJTree: Do not edit this line. ASTskipt_do_not_consume_last.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTskipt_do_not_consume_last extends SimpleNode {
  public ASTskipt_do_not_consume_last(int id) {
    super(id);
  }

  public ASTskipt_do_not_consume_last(YAL2JVM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7d3eff94a1bac0f95c50e15cb663e2e6 (do not edit this line) */
