/* Generated By:JJTree: Do not edit this line. ASTScalarElement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTScalarElement extends SimpleNode {
  public ASTScalarElement(int id) {
    super(id);
  }

  public ASTScalarElement(YAL2JVM p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=27753f66ca68e94b63f02f692c1ebc2c (do not edit this line) */
