/* Generated By:JJTree: Do not edit this line. ASTskipt_do_not_consume_last.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTskipt_do_not_consume_last extends SimpleNode {
  public ASTskipt_do_not_consume_last(int id) {
    super(id);
  }

  public ASTskipt_do_not_consume_last(YAL2JVM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YAL2JVMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1cacbca8a4753ebead3e7f94745a650a (do not edit this line) */
