/* Generated By:JJTree: Do not edit this line. ASTVarlist.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarlist extends SimpleNode {
  public ASTVarlist(int id) {
    super(id);
  }

  public ASTVarlist(YAL2JVM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(YAL2JVMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ae682ee5fd8df7a7f4b85efe6739d33e (do not edit this line) */
