all:
	jjtree yal2jvm.jjt
	@echo
	@echo
	@echo JJTREE SUCCESSFULLY COMPILED
	@echo
	@echo
	javacc yal2jvm.jj
	@echo
	@echo
	@echo JAVACC SUCCESSFULLY COMPILED
	@echo
	@echo
	javac *.java
	@echo
	@echo
	@echo JAVAC SUCCESSFULLY COMPILED
	@echo
	@echo
