/* Generated By:JavaCC: Do not edit this line. YAL2JVMTreeConstants.java Version 6.0_1 */
public interface YAL2JVMTreeConstants
{
  public int JJTSKIPT_DO_NOT_CONSUME_LAST = 0;
  public int JJTERROR_CONTROL = 1;
  public int JJTMODULE = 2;
  public int JJTDECLARATION = 3;
  public int JJTFUNCTION = 4;
  public int JJTVARLIST = 5;
  public int JJTARRAYELEMENT = 6;
  public int JJTSCALARELEMENT = 7;
  public int JJTSTMTLST = 8;
  public int JJTSTMT = 9;
  public int JJTASSIGN = 10;
  public int JJTLHS = 11;
  public int JJTRHS = 12;
  public int JJTARRAYSIZE = 13;
  public int JJTTERM = 14;
  public int JJTEXPRTEST = 15;
  public int JJTWHILE = 16;
  public int JJTIF = 17;
  public int JJTCALL = 18;
  public int JJTCALLSTMT = 19;
  public int JJTARGUMENTLIST = 20;
  public int JJTARGUMENT = 21;
  public int JJTARRAYACCESS = 22;
  public int JJTSCALARACCESS = 23;
  public int JJTINDEX = 24;
  public int JJTERRORBLOCK = 25;


  public String[] jjtNodeName = {
    "skipt_do_not_consume_last",
    "error_control",
    "Module",
    "Declaration",
    "Function",
    "Varlist",
    "ArrayElement",
    "ScalarElement",
    "Stmtlst",
    "Stmt",
    "Assign",
    "Lhs",
    "Rhs",
    "ArraySize",
    "Term",
    "Exprtest",
    "While",
    "If",
    "Call",
    "CallStmt",
    "ArgumentList",
    "Argument",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
    "ErrorBlock",
  };
}
/* JavaCC - OriginalChecksum=646a22d3630dda791a00e69a1c6d3dde (do not edit this line) */
